import { PageConfigSchema, type PageConfig, type UiEndpoint } from "./page-config.js";

const buttonPosition = (rowIndex: number) => ({
  unit: "percent" as const,
  x: 4,
  y: 4 + rowIndex * 9,
  width: 20,
  height: 7,
});

const percentPosition = (x: number, y: number, width: number, height: number) => ({
  unit: "percent" as const,
  x,
  y,
  width,
  height,
});

const createPageConfig = (
  id: string,
  name: string,
  path: string,
  roleScope: UiEndpoint,
  components: PageConfig["components"] = [],
): PageConfig => ({
  id,
  name,
  path,
  roleScope,
  layout: { type: "freeform", gap: 12, padding: 24 },
  components,
});

export const defaultPageConfigs = [
  createPageConfig("shared.profile", "个人主页", "/own_page", "player"),
  createPageConfig("player.home", "玩家主界面", "/", "player", [
    {
      id: "player.profile.button",
      type: "button",
      label: "个人主页",
      icon: "user",
      position: buttonPosition(0),
      action: { type: "navigate", targetPageId: "shared.profile", targetPath: "/own_page" },
    },
    {
      id: "player.community.button",
      type: "button",
      label: "社区大厅",
      icon: "message-circle",
      position: buttonPosition(1),
      action: { type: "navigate", targetPageId: "player.community", targetPath: "/community_hall" },
    },
    {
      id: "player.shop.button",
      type: "button",
      label: "玩家商店",
      icon: "shopping-bag",
      position: buttonPosition(2),
      action: { type: "navigate", targetPageId: "player.shop", targetPath: "/player_shop" },
    },
  ]),
  createPageConfig("player.community", "社区大厅", "/community_hall", "player"),
  createPageConfig("player.shop", "玩家商店", "/player_shop", "player"),

  createPageConfig("designer.home", "设计师主界面", "/", "designer", [
    {
      id: "designer.home.dashboard",
      type: "panel",
      kind: "container",
      position: percentPosition(2, 3, 96, 94),
      style: {
        backgroundColor: "#fffdfa",
        borderRadius: 14,
      },
      childComponentIds: [
        "designer.home.heroTitle",
        "designer.home.heroCopy",
        "designer.home.settingsButton",
        "designer.home.stage",
      ],
    },
    {
      id: "designer.home.heroTitle",
      type: "text",
      text: "设计师主界面",
      position: percentPosition(3, 3, 28, 8),
      style: {
        backgroundColor: "#ffffff",
        textColor: "#12202f",
        borderRadius: 10,
        fontSize: 22,
      },
    },
    {
      id: "designer.home.heroCopy",
      type: "text",
      text: "欢迎，{{nickname}}。链条式关卡是主舞台，功能以角落按钮展开。",
      position: percentPosition(3, 11, 62, 7),
      style: {
        backgroundColor: "#ffffff",
        textColor: "#3e544f",
        borderRadius: 10,
      },
    },
    {
      id: "designer.home.settingsButton",
      type: "button",
      label: "设置",
      icon: "settings",
      position: percentPosition(86, 5, 10, 6),
      style: {
        variant: "secondary",
        borderRadius: 10,
      },
      action: { type: "none" },
    },
    {
      id: "designer.home.stage",
      type: "panel",
      kind: "stage",
      position: percentPosition(3, 22, 94, 74),
      style: {
        backgroundColor: "#eef5ef",
        borderRadius: 14,
      },
      childComponentIds: [
        "designer.home.stageTitle",
        "designer.home.userMeta",
        "designer.home.identityButton",
        "designer.home.stageSettingsButton",
        "designer.home.mapViewport",
        "designer.home.actionButton",
        "designer.home.actionPanel",
      ],
    },
    {
      id: "designer.home.stageTitle",
      type: "text",
      text: "Level Chain",
      position: percentPosition(3, 2, 16, 7),
      style: {
        backgroundColor: "#eef5ef",
        textColor: "#12202f",
        borderRadius: 10,
        fontSize: 18,
      },
    },
    {
      id: "designer.home.userMeta",
      type: "text",
      text: "当前用户 ID：{{apiUserId}}",
      position: percentPosition(23, 2, 30, 6),
      style: {
        backgroundColor: "#f7faf5",
        textColor: "#3e544f",
        borderRadius: 10,
      },
    },
    {
      id: "designer.home.identityButton",
      type: "button",
      label: "身份",
      icon: "user",
      position: percentPosition(3, 10, 10, 7),
      style: {
        variant: "secondary",
        borderRadius: 10,
      },
      action: { type: "none" },
    },
    {
      id: "designer.home.stageSettingsButton",
      type: "button",
      label: "设置",
      icon: "settings",
      position: percentPosition(87, 10, 10, 7),
      style: {
        variant: "secondary",
        borderRadius: 10,
      },
      action: { type: "none" },
    },
    {
      id: "designer.home.mapViewport",
      type: "panel",
      kind: "stage",
      position: percentPosition(6, 18, 88, 62),
      style: {
        backgroundColor: "#f4f9ff",
        borderRadius: 14,
      },
      childComponentIds: [
        "designer.home.mapTitle",
        "designer.home.level01",
        "designer.home.level02",
        "designer.home.level03",
        "designer.home.level04",
        "designer.home.level05",
        "designer.home.level06",
        "designer.home.level07",
        "designer.home.level08",
      ],
    },
    {
      id: "designer.home.mapTitle",
      type: "text",
      text: "关卡主舞台",
      position: percentPosition(4, 4, 18, 10),
      style: {
        backgroundColor: "#f4f9ff",
        textColor: "#12385f",
        borderRadius: 10,
        fontSize: 18,
      },
    },
    {
      id: "designer.home.level01",
      type: "button",
      label: "01 草地训练场",
      icon: "circle",
      position: percentPosition(7, 22, 16, 12),
      style: { variant: "primary", borderRadius: 999 },
      action: { type: "none" },
    },
    {
      id: "designer.home.level02",
      type: "button",
      label: "02 风桥回旋点",
      icon: "circle",
      position: percentPosition(20, 42, 16, 12),
      style: { variant: "primary", borderRadius: 999 },
      action: { type: "none" },
    },
    {
      id: "designer.home.level03",
      type: "button",
      label: "03 高塔猪舍",
      icon: "circle",
      position: percentPosition(34, 24, 16, 12),
      style: { variant: "ghost", borderRadius: 999 },
      action: { type: "none" },
    },
    {
      id: "designer.home.level04",
      type: "button",
      label: "04 玻璃深谷",
      icon: "circle",
      position: percentPosition(48, 42, 16, 12),
      style: { variant: "ghost", borderRadius: 999 },
      action: { type: "none" },
    },
    {
      id: "designer.home.level05",
      type: "button",
      label: "05 双城核心",
      icon: "circle",
      position: percentPosition(62, 24, 16, 12),
      style: { variant: "ghost", borderRadius: 999 },
      action: { type: "none" },
    },
    {
      id: "designer.home.level06",
      type: "button",
      label: "06 暮色仓场",
      icon: "circle",
      position: percentPosition(74, 42, 16, 12),
      style: { variant: "ghost", borderRadius: 999 },
      action: { type: "none" },
    },
    {
      id: "designer.home.level07",
      type: "button",
      label: "07 碎岩坡道",
      icon: "circle",
      position: percentPosition(36, 66, 16, 12),
      style: { variant: "ghost", borderRadius: 999 },
      action: { type: "none" },
    },
    {
      id: "designer.home.level08",
      type: "button",
      label: "08 寒雾驿站",
      icon: "circle",
      position: percentPosition(58, 66, 16, 12),
      style: { variant: "ghost", borderRadius: 999 },
      action: { type: "none" },
    },
    {
      id: "designer.home.actionButton",
      type: "button",
      label: "创作",
      icon: "plus",
      position: percentPosition(85, 84, 10, 8),
      style: {
        variant: "primary",
        borderRadius: 10,
      },
      action: { type: "openPanel", panelId: "designer.home.actionPanel" },
    },
    {
      id: "designer.home.actionPanel",
      type: "panel",
      kind: "overlay",
      position: percentPosition(66, 55, 24, 28),
      style: {
        backgroundColor: "#fffdfa",
        borderRadius: 12,
      },
      childComponentIds: [
        "designer.home.actionPanelTitle",
        "designer.home.profileButton",
        "designer.home.createMapButton",
        "designer.home.birdLabButton",
      ],
    },
    {
      id: "designer.home.actionPanelTitle",
      type: "text",
      text: "功能入口",
      position: percentPosition(8, 6, 48, 14),
      style: {
        backgroundColor: "#fffdfa",
        textColor: "#12202f",
        borderRadius: 10,
        fontSize: 16,
      },
    },
    {
      id: "designer.home.profileButton",
      type: "button",
      label: "个人主页",
      icon: "user",
      position: percentPosition(8, 26, 66, 14),
      style: { variant: "secondary", borderRadius: 10 },
      action: { type: "navigate", targetPageId: "shared.profile", targetPath: "/own_page" },
    },
    {
      id: "designer.home.createMapButton",
      type: "button",
      label: "创造地图",
      icon: "map",
      position: percentPosition(8, 46, 66, 14),
      style: { variant: "primary", borderRadius: 10 },
      action: { type: "navigate", targetPageId: "designer.design", targetPath: "/designer/design" },
    },
    {
      id: "designer.home.birdLabButton",
      type: "button",
      label: "鸟类开发",
      icon: "bird",
      position: percentPosition(8, 66, 66, 14),
      style: { variant: "ghost", borderRadius: 10 },
      action: { type: "none" },
    },
  ]),
  createPageConfig("designer.design", "创造地图", "/designer/design", "designer"),
  createPageConfig("designer.settings", "设置", "/designer/design/settings", "designer"),
  createPageConfig("designer.designBook", "设计手册", "/designer/design/design_book", "designer"),
  createPageConfig("designer.jsonCheck", "JSON 检查", "/designer/design/json_check", "designer"),
  createPageConfig("designer.archive", "归档备份", "/designer/design/archive_{backupId}", "designer"),
  createPageConfig(
    "designer.archiveJsonCheck",
    "归档 JSON 检查",
    "/designer/design/archive_{backupId}/json_check",
    "designer",
  ),

  createPageConfig("admin.home", "管理员主界面", "/", "admin", [
    {
      id: "admin.profile.button",
      type: "button",
      label: "个人主页",
      icon: "user",
      position: buttonPosition(0),
      action: { type: "navigate", targetPageId: "shared.profile", targetPath: "/own_page" },
    },
    {
      id: "admin.community.button",
      type: "button",
      label: "社区管理",
      icon: "messages-square",
      position: buttonPosition(1),
      action: { type: "navigate", targetPageId: "admin.community", targetPath: "/community_hall" },
    },
    {
      id: "admin.proposals.button",
      type: "button",
      label: "提案处理",
      icon: "clipboard-check",
      position: buttonPosition(2),
      action: { type: "navigate", targetPageId: "admin.proposals", targetPath: "/admin/proposals" },
    },
  ]),
  createPageConfig("admin.community", "社区管理", "/community_hall", "admin"),
  createPageConfig("admin.proposals", "提案处理", "/admin/proposals", "admin", [
    {
      id: "admin.proposals.shell",
      type: "panel",
      title: "{{nickname}}的提案处理工作区",
      position: percentPosition(4, 6, 92, 86),
      style: {
        variant: "secondary",
        backgroundColor: "#fffdfa",
        borderRadius: 14,
      },
      childComponentIds: [
        "admin.proposals.title",
        "admin.proposals.refresh",
        "admin.proposals.pendingPanel",
        "admin.proposals.detailPanel",
      ],
    },
    {
      id: "admin.proposals.title",
      type: "text",
      text: "{{roleLabel}}预览账号 {{nickname}} 正在查看设计师提交的关卡提案。",
      position: percentPosition(3, 5, 54, 10),
      style: {
        backgroundColor: "#f4f9ff",
        textColor: "#12385f",
        borderRadius: 10,
      },
    },
    {
      id: "admin.proposals.refresh",
      type: "button",
      label: "刷新提案",
      icon: "refresh-cw",
      position: percentPosition(73, 6, 20, 8),
      style: {
        variant: "primary",
        borderRadius: 10,
      },
      action: { type: "none" },
    },
    {
      id: "admin.proposals.pendingPanel",
      type: "panel",
      title: "待审核列表",
      position: percentPosition(3, 20, 42, 72),
      style: {
        backgroundColor: "#f7faf5",
        borderRadius: 12,
      },
      childComponentIds: [
        "admin.proposals.pendingText",
        "admin.proposals.openDetail",
      ],
    },
    {
      id: "admin.proposals.pendingText",
      type: "text",
      text: "待审核提案将按 {{apiUserId}} 的权限范围加载。这里用于检查真实账号视角下的列表排布。",
      position: percentPosition(6, 10, 84, 28),
      style: {
        backgroundColor: "#ffffff",
        textColor: "#3e544f",
        borderRadius: 10,
      },
    },
    {
      id: "admin.proposals.openDetail",
      type: "button",
      label: "打开详情面板",
      icon: "panel-right-open",
      position: percentPosition(6, 70, 52, 12),
      style: {
        variant: "secondary",
        borderRadius: 10,
      },
      action: { type: "openPanel", panelId: "admin.proposals.detailPanel" },
    },
    {
      id: "admin.proposals.detailPanel",
      type: "panel",
      title: "提案详情",
      position: percentPosition(49, 20, 48, 72),
      style: {
        backgroundColor: "#fff8ef",
        borderRadius: 12,
      },
      childComponentIds: [
        "admin.proposals.detailText",
        "admin.proposals.reviewPanel",
      ],
    },
    {
      id: "admin.proposals.detailText",
      type: "text",
      text: "{{nickname}} 可以在这里预览提案、填写审核备注，并执行通过或拒绝。",
      position: percentPosition(5, 8, 88, 18),
      style: {
        backgroundColor: "#ffffff",
        textColor: "#5f4a2e",
        borderRadius: 10,
      },
    },
    {
      id: "admin.proposals.reviewPanel",
      type: "panel",
      title: "审核操作",
      position: percentPosition(5, 36, 88, 48),
      style: {
        backgroundColor: "#f4f9ff",
        borderRadius: 12,
      },
      childComponentIds: [
        "admin.proposals.approve",
        "admin.proposals.reject",
      ],
    },
    {
      id: "admin.proposals.approve",
      type: "button",
      label: "通过",
      icon: "check",
      position: percentPosition(8, 22, 34, 18),
      style: {
        variant: "primary",
        borderRadius: 10,
      },
      action: { type: "none" },
    },
    {
      id: "admin.proposals.reject",
      type: "button",
      label: "拒绝",
      icon: "x",
      position: percentPosition(52, 22, 34, 18),
      style: {
        variant: "ghost",
        borderRadius: 10,
      },
      action: { type: "none" },
    },
  ]),

  createPageConfig("director.home", "总监主界面", "/", "director", [
    {
      id: "director.profile.button",
      type: "button",
      label: "个人主页",
      icon: "user",
      position: buttonPosition(0),
      action: { type: "navigate", targetPageId: "shared.profile", targetPath: "/own_page" },
    },
    {
      id: "director.workbench.button",
      type: "button",
      label: "总监工作台",
      icon: "settings",
      position: buttonPosition(1),
      action: { type: "navigate", targetPageId: "director.workbench", targetPath: "/director_console" },
    },
  ]),
  createPageConfig("director.workbench", "总监工作台", "/director_console", "director"),
  createPageConfig(
    "director.uiCustomization",
    "UI 美化配置",
    "/director_console/ui_customization",
    "director",
  ),
] satisfies PageConfig[];

export const DefaultPageConfigsSchema = PageConfigSchema.array();

export const getDefaultPageConfigs = (): PageConfig[] =>
  DefaultPageConfigsSchema.parse(defaultPageConfigs);
